# Generated by Django 4.0.3 on 2022-04-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0002_power'),
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supers',
            name='primary_ability',
        ),
        migrations.RemoveField(
            model_name='supers',
            name='secondary_ability',
        ),
        migrations.AddField(
            model_name='supers',
            name='power_ability',
            field=models.ManyToManyField(to='super_types.power'),
        ),
    ]
