# Generated by Django 4.0.3 on 2022-04-04 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0003_rename_super_type_id_supers_super_types_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supers',
            old_name='super_types_id',
            new_name='super_types',
        ),
    ]
